name: Build and Publish AAR to JitPack

on:
  push:
    tags:
      - 'v*'  # Trigger on any tag starting with "v" (e.g., v1.0.0)

jobs:
  build_and_publish:
    runs-on: ubuntu-latest

    steps:
      # Step 1: Checkout the repository
      - name: Checkout code
        uses: actions/checkout@v2

      # Step 2: Set up SSH key to clone private repositories (if required)
      - name: Set up SSH key for Git operations
        run: |
          mkdir -p ~/.ssh  # Create the .ssh directory if it doesn't exist
          echo "$GIT_SSH_PRIVATE_KEY" > ~/.ssh/id_rsa  # Write the private key to id_rsa
          chmod 600 ~/.ssh/id_rsa  # Set the correct permissions for the private key
          ssh-keyscan github.com >> ~/.ssh/known_hosts  # Add GitHub's SSH key to known_hosts
        env:
          GIT_SSH_PRIVATE_KEY: ${{ secrets.GIT_SSH_PRIVATE_KEY }}

      # Step 3: Set up JDK 11 (required for Android Gradle builds)
      - name: Set up JDK 11
        uses: actions/setup-java@v2
        with:
          java-version: '11'

      # Step 4: Build the .aar file
      - name: Build .aar file
        run: |
          ./gradlew clean assembleRelease

      # Step 5: Publish to JitPack
      - name: Publish to JitPack
        run: |
          # Set the version dynamically from the tag
          echo "version=${GITHUB_REF#refs/tags/}" >> gradle.properties
          echo "group=com.github.Saidazizkhon05" >> gradle.properties
          echo "archivesBaseName=sdk" >> gradle.properties
          ./gradlew publish

      # Step 6: Notify success
      - name: Notify success
        run: echo "Successfully built and published the .aar file to JitPack!" 
