name: CI/CD - Build & Release SDK

on:
  push:
    tags:
      - 'v*'  # Only runs when a tag like v1.0.0 is pushed

jobs:
  build:
    name: Build SDK
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v3

      - name: Set up JDK
        uses: actions/setup-java@v3
        with:
          distribution: 'temurin'
          java-version: 17

      - name: Grant Execute Permission for Gradle
        run: chmod +x gradlew

      - name: Build SDK (.aar)
        run: ./gradlew mylibrary:clean mylibrary:assembleRelease

      - name: Upload Build Artifact
        uses: actions/upload-artifact@v4
        with:
          name: mylibrary-release.aar
          path: mylibrary/build/outputs/aar/mylibrary-release.aar

  release:
    name: Release SDK
    needs: build
    runs-on: ubuntu-latest
    permissions:
      contents: write  # Required to push releases

    steps:
      - name: Checkout Code
        uses: actions/checkout@v3

      - name: Set up JDK
        uses: actions/setup-java@v3
        with:
          distribution: 'temurin'
          java-version: 17

      - name: Grant Execute Permission for Gradle
        run: chmod +x gradlew

      - name: Build SDK (.aar)
        run: ./gradlew mylibrary:clean mylibrary:assembleRelease

      - name: Publish Release
        uses: softprops/action-gh-release@v1
        with:
          tag_name: ${{ github.ref_name }}  # Uses the pushed tag as release version
          files: mylibrary/build/outputs/aar/mylibrary-release.aar
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
